config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#delete'

  root 'sessions#new'
  resources :posts
  resources :users
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  EMAIL_FORMAT = /\w+@\w+\.\w+/i
  validates :email, presence: true, format: { with: EMAIL_FORMAT}, uniqueness: true

  has_secure_password

  has_many :posts, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index
		if params[:category].blank?
			@posts = Post.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@posts = Post.where(category_id: @category_id).order("created_at DESC")
		end
	end
	
	def show
	end
	
	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user = current_user

		if @post.save
			redirect_to @post, notice: "The post was created!"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post, notice: "Update successfully!"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path, notice: "Post destoryed!"
	end

	private
	def post_params
		params.require(:post).permit(:title, :content, :category_id)
	end

	def find_post
		@post = Post.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to posts_path
    else
      flash.now[:danger] = 'Bad email/password combination. Try again.'
      render 'new'
    end
  end

  def delete
  	session.delete(:user_id)
  	@current_user = nil
  	redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created. Try to log in!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  <title>Testapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <% if current_user %>
      Hi <%= current_user.name %>
      |
      <%= link_to 'Log out', logout_path, method: :delete %>
    <% else %>
      <%= link_to 'Log in', login_path %>
      |
      <%= link_to 'Sign up', new_user_path %>
    <% end %>
  </header>
  <div class="row padding: 5px">
  <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
     <%= render 'shared/error_messages' %>
     <%= f.collection_select(:category_id, Category.all, :id, :name, {prompt: 'Choose a category' }) %><br>
     <%= f.label :title %><br>
     <%= f.text_field :title, placeholder: 'Type the post title here' %><br>
     <%= f.label :content %><br>
     <%= f.text_area :content, size: '60x12', placeholder: 'Type the post tect here' %><br>
 
     <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<head>
  <h1 class="posts_title"> Posts </h1>
  <nav>
    <div class='container-fluid'>
      <%= render 'shared/nav' %>
    </div>
  </nav>
  <div class='menu_right'>
  <%= link_to 'New Post', new_post_path %>
  </div>
  <div class="row padding: 5px">
  <%= yield %>
  </div>
  <div class='menu_right'>
  <%= link_to 'Back', posts_path %>
  </div>
</head>
<% @posts.each do |post| %>
     <h1><%= link_to post.title, post %></h1>
     <p>Author: <%= link_to post.user.name, post.user %> Updated at: <%= post.updated_at %></p>
     <p><%= post.content %></p>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<%= link_to "Edit", edit_post_path %>
<%= link_to "Delete", @post, method: :delete, data: { confirm: "Are you sure?" } %>
<%= link_to "Back", posts_path %>

app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
     <div>
          <p><%= pluralize(@post.errors.count, "error") %> prevented this post from saving.</p>
          <ul>
               <% @post.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
               <% end %>
          </ul> 
     </div>
<% end %>

app/views/shared/_nav.html.erb
<% Category.all.each do |category| %>
  <li>
  <%= link_to category.name, posts_path(category: category.name) %>
  </li>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :name %>
    <%= f.text_field :name %>
    </br>

    <%= f.label :email %>
    <%= f.text_field :email %>
    </br>

    <%= f.label :password %>
    <%= f.password_field :password %>
    </br>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
    </br>


    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="1">User</th>
      <th colspan="1">Email</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>  
        <td><%= link_to 'Edit', edit_user_path(user) %></td>  
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @user.name %></h1>

<% @user.posts.each do |post| %>
  <h2><%= link_to post.title, post %></h2>
  <p><%= post.content.truncate(100) %></p>
<% end %>
<%= link_to 'Back', posts_path %>